[application]


[web.app]

# HTML title tag content
title = "blog"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[android]

[project]
app_name = "VehiclesApp"
